# The level to log information at. The higher the level, the less you will see.
# We do not recommend setting it higher than WARNING, but support it.
# Valid levels: DEBUG, INFO, WARNING, ERROR, CRITICAL
log_level: "DEBUG"

# The game mode the bot should play.
# Currently valid game modes: normal
# Please note that changing this may require changing traits as well.
game_mode: "normal"

# Timeout for the bot to stay in the queue. 
# This is the maximum time the bot will wait in the queue before it will exit the queue, in seconds.
queue_timeout: 150

# The traits you want the bot to roll for.
# The trait names are almost as written in-game, with spaces replaced by _ and . and : being ignored.
# For example: admin, star_guardian, mecha_prime, lasercorps
# For a full list of valid traits, visit https://github.com/TeamFightTacticsBots/Alune/tree/main/alune/images/traits
traits:
  - shadow_isles
  - warden

# Determines whether the bot should surrender as soon as possible (after round 3-1)
# Valid values : true, false
# Default value : false
surrender_early: true

# The bot will pick a random number between 1 and surrender_random_delay.
# The bot will then add that number as a delay before it surrenders.
# Default value : 0 (disabled = surrender as fast as possible)
surrender_random_delay: 60

# Screen recording settings.
screen_record:
  # Whether we should use screen recording.
  # If false, the bot will fall back to screen capture.
  # Screen recording saves ~600ms per screen check, but may occasionally cause a timeout.
  # The timeout will be caught and handled.
  enabled: true

# Configuration for chance events in the bot, in percent.
chances:
  # The chance % to buy experience per check - configuring 50 means it's a 50% chance.
  # Alune will never try to buy XP when it can't.
  buy_xp: 50


# Override the default ADB port Alune tries to connect to.
# If there is no device listening on this port, a scan will happen to find your device.
adb_port: 5555

# Changing these below values manually can potentially break the bot, so don't!
# Version of the YAML.
version: 11
# Version of the TFT set.
set: 16
